### PR TITLE
WIP - HTTPTupleRequest 

### PR DESCRIPTION
**Pull request by siegenth**
This has been implemented to process REST calls by Streams. Request comes in from the web, tuple is generated to the output port; processing happens; input port gets results and a web response web originator is sent.  

This is a work in progress. 

I wanted to extend from ServletOperator class in order that I share the Jetty server and get the security features already done (maybe). The issue I ran into, all the classes that extend ServletOperator push messages to Jetty. This operator is driven by Jetty (callbacks), any pointers o would be appreciated. 

I have tests but their python clients, I' need to get them into the framework with the supporting spl. That is next.

### CODE REVIEW

**Comment by ddebrunner** [comment]
I'll take a look at this ...

**Comment by ddebrunner** [comment]
@siegenth It would help if there was a simple diagram showing the flow of HTTP request and tuple flow and response, and which Java classes are involved.

That or maybe descriptions for each Java class stating its purpose/role in a request/response.

Minor point that most(all) the tracing at `info` should probably be at `debug`.

**Comment by siegenth** [comment]
I added comments to all the classes on the most recent push, no code updates. , The `HTTPTupleRequest` is the entry point for the operator and now for comments as well. `ReqHandlerSuspend` does the heavy lifting with  a dependency Jetty that drives the processing, I tried to outline what is going with the class. 

`opt/testPython/HTTPTupleRequest/basicTests.py` has a comment that includes an ASCII diagram of the basic flow being tested. I'll pull this out and check in a 'real' diagram since this is the fundamental pattern for all requests using this operator.  I was told the the spldoc can handle the image.

**Comment by ddebrunner** [comment]
Just a reference to the continuations the operator uses:

http://www.eclipse.org/jetty/documentation/9.4.x/continuations.html

(though it's not using 9.4 at the moment)

**Comment by ddebrunner** [comment]
I changed the target branch to a new `rest_response_op` branch to act as a feature branch.

**Comment by ddebrunner** [comment]
Merge as initial point for feature dev.

**Pull request merged**
