### PR TITLE
FTP Operators in inet toolkit

### PR DESCRIPTION
**Pull request by joergboe**
The FTP operators:
-FTPReader
-FTPCommand
-FTPPutFile
are now available in inet toolkit.
This includes an wrapper libray libftpwrapper
and 2 samples
-PutFile
-RemodeDirScanAndGet

### CODE REVIEW

**Comment by hildrum** [comment]
It looks good to me.  @chanskw  Any objections?

**Comment by hildrum** [comment]
Heard from @chanskw  off of github that she was okay with merging.

**Comment by chanskw** [comment]
Hi -

+ 1 for the operators.  Thanks for the contribution.

No, we do not need to bump version number.  But it is ok if you already did.  We only need to bump version once a release.  We haven't done a release yet.

I haven't had a chance to look at the code, but couple of questions:
1)  Are these operators targeted for Streams 3.2.1?
2)  @hildrum , are these operators affected by the application bundle and consistent region feature from Streams 3.2.2 release?

Thanks...
Samantha

**Comment by chanskw** [comment]
Copyright on the files should say 2014, if they are created in 2014.  It currently says 2013-2014.

**Comment by hildrum** [comment]
@joergboe  -- I think it would be good if you could issue another pull request against the Streams 3.2.1 branch, so we can pull these operators in there as well as into the master. @chanskw what do you think?

Inspired by @chanskw's comment, I went looking for things that would be a potential problem in Streams 3.2.2.  You don't have any consistent cut support, but I don't think it make sense to hold up adding these operators to wait for that.  However, I notice that there may be a problem with the localFilename parameter of FTPPutFile--see issue #87.

**Comment by hildrum** [comment]
Also @joergboe any particular reason you used an enum rather than a custom literal for `connectionCloseMode` in FTPCommand, FTPPutFile, and FTPReader?  Same question about `protocol` in FTPPutFile and FTPReader.

**Comment by chanskw** [comment]
I think it's a good idea to put the code in the Streams 3.2.1 branch.

In thinking about this more, if the operators are not ready for 3.2.2, perhaps this should be contributed to the 3.2.1 branch alone initially.  Once we are sure that the operators will work in 3.2.2, then we will put it into the master branch. 

Is that a good approach?  Or will it be too confusing?

**Comment by joergboe** [comment]
- The operators desinged for rel 3.2. Thus they should be also in the branch 3.2.

- I made a quick test to sure that they work also in rel 4.0. The operators passed this test.
But yes: They are not designed for consistent cut and the data directory may be a potential problem in rel 4.0. It need effort to overcome this.

- Yes there are reasons to use enum for protocol and connectionCloseMode. My intention was, that these parameters can be determined at sumbission time rathen than at compile time. And it is hard to acces the types of the custom literals in SPL code level (The original design was made with rel 2.x). But you need the type of these parameters to cast the submission time input string into the type of the particular parameter. Thus an public enum type was the solution to achive this.

**Comment by hildrum** [comment]
I think we can roll back the master branch to a point before I accepted the pull request, and thus back these out of 3.2.2 if that's the decision.

However, I do think they should be in 3.2.2.    They are not broken in 3.2.2, they are just not as nice as they could be.  I do feel a little uncomfortable about the localFilename parameter handling, but that's only one or two lines of code, and so worth fixing to make the whole toolkit available in 3.2.2.

Consistent cut handling would require more work that we might not have time to do.  But I think it'd better to have these operators available in 3.2.2 but not usable in a consistent region than to have them not available in 3.2.2 at all.  The FTPCommand operator probably doesn't make sense in a consistent region in any case.

**Comment by chanskw** [comment]
I agree that they are useful for 3.2.2.  If they work in general in 3.2.2, then we should keep them in.

**Comment by joergboe** [comment]
I agree with that. Filename handling can be fixed with less effort.

**Pull request merged**
