### PR TITLE
Cleaned up and enhanced OpenLayers mapping code

### PR DESCRIPTION
**Pull request by ulemanstreaming**
Rewrote much of the layer and marker update code.
- Switched from a marker layer to a vector layer for the dynamic points
- External graphics (icons)  now load directly from file; data must
specify filename instead of color name (defaults to blue marker)
- Added graphics for "award" and blue marker
- Added ability to load polygons (geofences) from a file and display
them in a polygon vector layer
- Reduced (but did not eliminate) a memory leak by moving and updating
the point vectors instead of recreating them on every update
- Cleaned up the popups a bit so they now update dynamically and move
with the points

### CODE REVIEW

**Comment by ddebrunner** [comment]
Thanks for improving the code.

Need to think a little about the removal of the simple default colour icons, that was for simplicity. It was also designed to allow the use of application specific file names so how is a file name provided in this new approach?

**Comment by ulemanstreaming** [comment]
@ddebrunner In the original, the Streams application populates an attribute called markerType with strings like "GREEN", "RED", etc. The code in openlayersutils.js branches on a small, predefined set of such words and loads the associated file into an icon object. GREEN -> marker-green.png, etc.

When I changed from makers to point vectors, I had to change how icons/images are managed. Vectors do not have an associated icon the way markers do. The easiest way I found (programming by Google) was to set a property called externalGraphic, which takes a file spec. At the same time, I made it so that a streams application must directly supply the file by populating the markertType attribute with actual file specs ("marker-green.png", etc.). 

This removes a level of indirection and makes the code less rigid. If I want more colors, I drop more graphics files into the resources directory and update my Streams app to take advantage of them, without messing with the js code.

I realize now that I broke backward compatibility. I would have cleaned that up if I had thought earlier about contributing my code back.

**Comment by ddebrunner** [comment]
I think the issue is that the user won't be able to drop additional icons into the resources directory as that's a shared toolkit, instead they should be able to include icons from their own toolkit.

I work on incorporating the externalGraphic with the markerEnum approach this afternoon, to at least maintain backward compat, but also (in the future) support arbitrary image files.

**Comment by ddebrunner** [comment]
Please don't merge this, I'm working on it.

**Comment by ddebrunner** [comment]
Closing this without merging as the change is now included in pull request #168

**Pull request closed without merging**
