### PR TITLE
Fix authentication for long userid:password

### LINKED ISSUE #146: Fix authentication for long userid:password
When using HTTPPost or HTTPGetStream, the BASE64 encoded string will have line breaks every 76 characters. When these line breaks are inserted into HTTP request headers, most HTTP servers get confused and return 400 (bad request).

### PR DESCRIPTION
**Pull request by alexpogue**
Fixes #146

### CODE REVIEW

**Comment by ddebrunner** [comment]
I know it's part of the existing code, but useridpassword.getBytes() can be troublesome as it uses the platform encoding, rather than a fixed encoding. Any idea if a fixed encoding is required, e.g. UTF-8?

**Comment by alexpogue** [comment]
Good catch. Apparently HTTP headers can only include ASCII characters, so UTF-8 will suffice to hold them. Fixed.

**Comment by ddebrunner** [comment]
Maybe a dumb question, but if HTTP requires ASCII characters, why not use StandardCharsets.US_ASCII  (ISO646-US) ?

**Comment by alexpogue** [comment]
@ddebrunner 
Whoa, I didn't realize US_ASCII was an option. Any non-ASCII characters in the header will be interpreted as binary data, but browsers don't agree on how to interpret the data (http://stackoverflow.com/a/5426648). Using US_ASCII is a good idea for documentation purposes, if nothing else. Fixed.

**Pull request merged**
