### PR TITLE
The changes to introduce the ant targets build-all-samples and clean-all-samples

### PR DESCRIPTION
**Pull request by joergboe**
Changes as discussed in issue 172
And changes to make all samples compile clean

### CODE REVIEW

**Comment by ddebrunner** [comment]
I think it's a little confusing to have two clean samples targets. I think it can be simplified so that the existing cleansamples targets calls two targets in its subant call, using nested target elements.

**Comment by joergboe** [comment]
I think the targets are consequential:
- the target 'all' builds the toolkit and indexes the samples and the toolkit and makes the doc, but it does not build the samples,
- I introduced the target 'build-all-samples' and 'clean-all-samples' to build and clean the samples,
- The targets 'samples' and 'cleansamples' make and clear only the toolkit-index. Probably we should re-name these targets to 'index-samples' and 'clean-samples-index'

**Comment by ddebrunner** [comment]
I think the only use case is cleaning the samples, not cleaning portions of the samples. The samples are applications, not reuseable toolkits so there's little value in just cleaning the application artifacts.

**Comment by ddebrunner** [comment]
I created pull request #181 to have a simple cleansamples target.

**Pull request merged**
