### PR TITLE
add parseDatestring() function to com.ibm.streamsx.inet 

### PR DESCRIPTION
**Pull request by ejpring**
This function converts a string that specifies a calendar date and time into an integer containing the corresponding 'unix epoch' value. It recognizes all of the date and time formats allowed in HTTP messages. For details, see [https://curl.haxx.se/libcurl/c/curl_getdate.html].

### CODE REVIEW

**Comment by ddebrunner** [comment]
Would this be better in the `com.ibm.streamsx.datetime` toolkit?

**Comment by ejpring** [comment]
I'm not sure you really want this parseDatestring() function in the datetime toolkit. The parseString() function has a dependency on the 'libcurl' library, which makes sense for the inet toolkit, but not the datetime toolkit. And it handles all of the date&time formats required by HTTP, but does not handle the ISO format used in the datetime toolkit.

**Comment by ddebrunner** [comment]
> integer containing the corresponding 'unix epoch' value

What units does it use?

**Comment by ejpring** [comment]
The parseString() function returns an SPL::int64 value that is the number of seconds since midnight on January 1st, 1970 in Greenwich, England. I'll add that to the description. I'll also copy the examples of date&time formats it recognizes from https://curl.haxx.se/libcurl/c/curl_getdate.html .

**Comment by ejpring** [comment]
Apparently, 'libcurl' renamed the CURLOPT_ACCEPT_ENCODING symbol from CURLOPT_ENCODING in version 7.21 . 

Unfortunately for Streams, RHEL/CentOS 6 distributes libcurl 7.19, and RHEL/CentOS 7 distributes libcurl 7.29 . This change ensures the InetSource operator will compile on both platforms.

**Pull request merged**
