### PR TITLE
[WIP] HTTPRequest operator.

### PR DESCRIPTION
**Pull request by ddebrunner**
Proposal in: https://github.com/IBMStreams/streamsx.inet/wiki/HTTPRequest-operator

Supports:
* GET (simple URL only)
* POST,PUT with `application/json`
* extra headers
* no authentication (except by extra headers)

### CODE REVIEW

**Comment by joergboe** [comment]
I would like to have a feature branch for that operator.
And once it completed and tested merge into master

**Comment by sadekjb** [comment]
The extra headers parameter in HTTPRequestOperAPI getting exception.
workaround by moving the extraHeaders to HTTPRequestOper class.

this is the exception:
Exception in thread "Thread-14" java.lang.IllegalStateException: CDISR5549E Class interface java.util.List not supported for @Parameter at method: public void com.ibm.streamsx.inet.http.HTTPRequestOper.setExtraHeaders(java.util.List)
        at com.ibm.streams.operator.internal.runtime.ParameterSetter.getSetterInternal(ParameterSetter.java:158)
        at com.ibm.streams.operator.internal.runtime.ParameterSetter.getSetter(ParameterSetter.java:108)
        at com.ibm.streams.operator.internal.runtime.ParameterSetter.set(ParameterSetter.java:82)
        at com.ibm.streams.operator.internal.runtime.OperatorAnnotations.applyParameters(OperatorAnnotations.java:157)
        at com.ibm.streams.operator.internal.runtime.OperatorAnnotations.applyRuntimeAnnotations(OperatorAnnotations.java:95)
        at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:731)
        at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)

**Comment by sadekjb** [comment]
seems this code in HTTPRequestOperAPI cause the exception:
    @Parameter(optional = true, description = "Extra headers to send with request, format is `Header-Name: value`.")
    public void setExtraHeaders(List<String> extraHeaders) {
        this.extraHeaders = extraHeaders;
    }

**Comment by ddebrunner** [comment]
@sadekjb Not sure what you are seeing, since `List<String>` is supported as a type for `@Parameter`.
There are uses in the existing operators.

**Comment by ddebrunner** [comment]
I'll work on creating a feature branch for this and bring the code up to date.

**Comment by joergboe** [comment]
Any updates for the code here?
I would like to start pushing this operator. Therefore I would start with:
1. create a feature branch in the main repository
2. pull this code into the feature branch
3. complete coding
4. add a sample
4. add client authentification
6. add OAuth2.0 support. Here I propose to use the apache oltu lib. Any suggestions

**Comment by joergboe** [comment]
The code of this PR is now in development branch : develop_httpreq

**Pull request closed without merging**
