### PR TITLE
make InetSource operator follow HTTP redirects, and add a bit more logging

### PR DESCRIPTION
**Pull request by ejpring**

### CODE REVIEW

**Comment by ddebrunner** [comment]
-1 on the trace level change to INFO. Tracing every HTTP request does not seem like a INFO level trace. INFO is really for occasional key informational items.

**Comment by ejpring** [comment]
Fair enough. I've changed the logging level back to L_DEBUG in InetSource.

That skips the log messages when the application's tracing level is 'L_INFO'. 

But Streams should log those messages when the operator's tracing level is 'L_DEBUG', but it doesn't. I've added this 'config' clause to the operator:


  stream<blob message, rstring url> RssInetStream = InetSource() {
    param
      URIList: getURLList($rssURLListFilename);
      fetchInterval: $rssFetchInterval;
      emitTuplePerURI: true; 
    **config
      logLevel: debug;
      tracing: debug;** }

 What am I missing?

**Comment by joergboe** [comment]
Config clause logLevel is deprecated use tracing instead.
Level trace is the most verbose. Some of your trace messages are L_TRACE

**Comment by ejpring** [comment]
I use SPLAPPTRC(L_TRACE, ...) for messages that include the contents of tuples, which can be very large, and SPLAPPTRC(L_DEBUG, ...) for less verbose messages.

I added "config logLevel: debug;" to my test application, even though its deprecated, to see if it would trigger tracing of SPLAPPTRC(L_DEBUG, ...) messages. It doesn't. Neither does "config tracing: debug;". Any idea why not?

**Comment by joergboe** [comment]
I'm using streams version 4.2.0.0.
I have checked out the master branch without you last pull request.
When I execute the samples/InetSource with tracing: trace
the I can see the traces:
14 Dec 2016 16:36:59.202 [16329] TRACE #splapptrc,J[7],P[7],Result,InetSource M[Result.cpp:process:794]  - got 413 bytes from URL http://weather.noaa.gov/pub/data/observations/metar/cycles/00Z.TXT ...
14 Dec 2016 16:36:59.202 [16329] DEBUG #splapptrc,J[7],P[7],Result,InetSource M[Result.cpp:process:921]  - Submitting output tuple with 'list<rstring>' data attribute{result=["<HTML><HEAD> <TITLE>Service Removed</TITLE> </HEAD><BODY>","<H1>This Service is no longer available</H1> In Accordance with <a href=\"http://www.nws.noaa.gov/om/notification/scn16-16wngccb.htm\">NWS Service Change Notice 16-16</a> this service has been discontinued.  Please see  <a href=\"http://www.weather.gov\">Weather.gov</a> and <a href=\"http://tgftp.nws.noaa.gov\">tgftp.nws.noaa.gov (raw data)</a>","</BODY></HTML>"]}
14 Dec 2016 16:36:59.202 [16329] TRACE #splapptrc,J[7],P[7],Result,InetSource M[Result.cpp:process:759]  - getting URL http://weather.noaa.gov/pub/data/observations/metar/cycles/01Z.TXT ...
14 Dec 2016 16:36:59.318 [16329] TRACE #splapptrc,J[7],P[7],Result,InetSource M[Result.cpp:process:794]  - got 413 bytes from URL http://weather.noaa.gov/pub/data/observations/metar/cycles/01Z.TXT ...
14 Dec 2016 16:36:59.318 [16329] DEBUG #splapptrc,J[7],P[7],Result,InetSource M[Result.cpp:process:921]  - Submitting output tuple with 'list<rstring>' data attribute{result=["<HTML><HEAD> <TITLE>Service Removed</TITLE> </HEAD><BODY>","<H1>This Service is no longer available</H1> In Accordance with <a href=\"http://www.nws.noaa.gov/om/notification/scn16-16wngccb.htm\">NWS Service Change Notice 16-16</a> this service has been discontinued.  Please see  <a href=\"http://www.weather.gov\">Weather.gov</a> and <a href=\"http://tgftp.nws.noaa.gov\">tgftp.nws.noaa.gov (raw data)</a>","</BODY></HTML>"]}
14 Dec 2016 16:36:59.318 [16329] TRACE #splapptrc,J[7],P[7],Result,InetSource M[Result.cpp:process:759]  - getting URL http://weather.noaa.gov/pub/data/observations/metar/cycles/02Z.TXT ...

**Comment by joergboe** [comment]
But when I use another url, the job shuts down!
Investigating

**Comment by ejpring** [comment]
OK. The 'URIList' parameter in the 'GetWeather.spl' sample application needs to be updated with a newer URLs. I'll handle that.

Can you post the URL that caused lnetSource to fail?

**Comment by joergboe** [comment]
I used the url:
"http://www.snafu.de"

This url causes a Malformed uri exception.

The the pe is shut down silently.
The 
SPLAPPLOG(L_ERROR, msg, "InetSource");
in the catch clause in MY_OPERATOR::checkURI method does not work 
or does not work in the exception handler

Thus I would like to add the statements:
SPLAPPTRC(L_ERROR, "DistilleryException: " << msg, "InetSource");
and 
SPLAPPTRC(L_ERROR, "std::exception: " << msg, "InetSource");
in the exception handler code.
These statments produce an ERROR in the trace facility and the user gets informed.

**Comment by ddebrunner** [comment]
Is tracing still not working for you? 

Tracing does work, so not sure what is going on.

**Comment by joergboe** [comment]
Consider to merge pull request #233

**Comment by joergboe** [comment]
Tracing works for me.
Logging in general works for me too.
But Logging make a problem probably in catch clause only

**Comment by joergboe** [comment]
The catch statements in method checkURI shold be improved.
When a exception is thrown the malformed uri is processed anyway.

**Comment by ejpring** [comment]
Yes, tracing is working as designed, just not as I'd like it to. 

The "--trace-level=3" parameter (for standalone applications) overrides the 'config tracing: debug;' clause I added to the InetSource operator. If I omit the parameter, the L_DEBUG statements in InetSource_cpp.cgt do get executed, but so do L_DEBUG statements in ProcessSignal.cpp and SubmitSignal.cpp. That clutters up the trace with hundreds of irrelevant messages per input tuple, which is what I was hoping to avoid.

**Pull request merged**
