### PR TITLE
Demonstration of the async operator

### PR DESCRIPTION
**Pull request by joergboe**
This pull request demonstrates the implementation of the asynchon http operation with streams means. This PR is not intended to be pulled. This is a demo. See issue #306 

The HTTPRequestAsyncComposite is the effective asynchronous operator implementation. The rest is the sample code for demonstration purpose.
This shows that the essential aspects of the async operator can be implemented with less than 100 spl code lines wihout any further external libs.
Threading and parallelism are the main aspects the spl language was designed for.

My proposal is to add such a lightweight composite operator to the inet toolkit.

### CODE REVIEW

**Comment by leongor** [comment]
+1
With one correction: by looking on the code it seems you're using http **sync** functions (and not async as declared).
So, it should be stated as:
This pull request demonstrates the implementation of the parallel synchonous http operations.

**Comment by joergboe** [comment]
> by looking on the code it seems you're using http sync functions (and not async as declared).
So, it should be stated as:
The http functions are synchronous, right, but in combination with a threaded port it becomes asynchronous and non blocking.
The threaded port queues the incoming tuple into the queue and spawns a separate thread for the operator logic.
Thus the PR demonstrates an asynchronous operation

**Comment by leongor** [comment]
No, it's not. It just delegates the sync part to the next thread, but the threaded port queue is not infinite, so once it's full the whole stream is stuck (with policy=wait).
Using policy=drop is not acceptable in most cases, because once the threaded port queue is full, on every  http request you are going to lose thousands of tuples.

**Comment by joergboe** [comment]
Now I'm helpless.
But one thing should be clear:
If any kind of client uses a resource in an asynchronous way (means the client does not wait for the synchronous response), then there is a congestion policy necessary (block, drop, queue, queue & block, queue & drop).
I'm quite confident that the cpp-netlib client implements one congestion mechanism. Otherwise it would require infinite resources. But unfortunately this is not transparent and it is hardly documented.
But when I look into the wiki:

> 

The asynchronous call approach can make HTTP/REST requests possible without blocking the thread. The responses will be handled as callbacks, in asynchronous manner when they arrive.

The Operator makes an HTTP(S) request for each tuple arriving on its input port.

The request is placed on a queue(s) and the calling thread is released

Each queue has a working thread that sends out the HTTP request with a callback to handle the response, keeping the input tuple data.

When the response arrives, it will call the callback with the response parameters (including the input tuple data)

This describes quite accurate what this PR implements.

**Comment by joergboe** [comment]
There is one feature 'HTTP pipelining' that allows to send more than one request over one connection before an response is received. This is intended to be used on transmission lines with high latency such as satellite connection. But I'm not sure if the cpp-netlib client uses this feature.

**Comment by leongor** [comment]
> This describes quite accurate what this PR implements

No, it doesn't. Look below.

> There is one feature 'HTTP pipelining' ...

cpp-netlib supports 'HTTP pipelining' only for a server, not client.

I understand that we probably don't talk about the same use case. Let me explain what I mean.
Here some sample stream schema: AnyOp -> ReSTCall
Let's suppose that AnyOp creates stream with a rate of 1000 tuples in a second.
Each tuple has 'url' attribute holding some ReST service uri to call (can be different or the same).

- Your solution with http sync functions

Let's say in your solution you open 10 parallel threads. Each thread calls httpGet function that sends the request and waits for the response. It doesn't matter how async you are before that call - **once there is a sync at the end, the whole stream is sync!**
Suppose each request takes 1 second. First 10 tuples are sent, then the whole stream is blocked for 1 second (policy=wait) or 1000 tuples are dropped (policy=drop). Then 10 next tuples are sent and so on...
**10 threads actually 99% of time only wait for response!**

- My solution with HTTPRequestAsync operator

By default it has only 1 thread with internal workQueue (can be easily increased with parameter).
Each tuple is sent **in async way to the http server**, so the http client thread doesn't wait for responses (never blocked). When a response arrives, a callback is called and submits a tuple to the output port.
The network latency is 0!
Here a [diagram](https://www.smashingmagazine.com/wp-content/uploads/2016/11/Ansychronous-Synchronous-requests-Android-preview-opt.png) showing a difference between the sync and async.

**Comment by joergboe** [comment]
ok we do not talk about pipelining and not talk about multiplexing (http2.0). That's fine because it simplifies the things.
So however you implement the async-client, the http protocol is synchronous in the end:
Each request will produce a apropriate response.
If you have a limited number of connections, and the processing of each request requires a certain amount of time, then you can not process an unlimitted number of requests in a given time. You has to queue, drop or block the request, which can not be executed from your system in the given time. This is a general system behavior.

**Comment by leongor** [comment]
You're right about HTTP being sync, but a single machine can handle few thousands TCP connections.
That will be a number of tuples that handled simultaneously.
With sync clients the max number of tuples will be as number of cores on that machine - ~10-20.

**Comment by joergboe** [comment]
Will come back soon with final version

**Pull request closed without merging**
