### PR TITLE
Fix for issue #103

### PR DESCRIPTION
**Pull request by conglisc**
Updated all samples' MakeFile to include toolkit location at ${STREAMS_INSTALL}/toolkits/com.ibm.streamsx.inet

### CODE REVIEW

**Comment by ddebrunner** [comment]
How will this work when someone is using a newer version of the toolkit that is not under $STREAMS_INSTALL?

**Comment by hildrum** [comment]
Did you make the same fix for v2.0.0?

**Comment by conglisc** [comment]
No, do you want me to do this for v2.0.0.0?

**Comment by hildrum** [comment]
I'm pulling this in.  @ddebrunner, it should work okay for someone using the newer version of the toolkit, unless they imported both the toolkit and the sample into StreamsStudio.

**Pull request merged**
